import type { Metadata } from 'next';
import './globals.css';
import ClientProvider from './provider';
import { Toaster } from '@/components/ui/sonner';
import { PopupProvider } from '@/components/constant/popup-context';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata: Metadata = {
  title: 'SuperAdmin',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className="bg-[#121212] antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <ClientProvider>
            <PopupProvider>{children}</PopupProvider>
          </ClientProvider>
        </ThemeProvider>
        <Toaster theme="dark" />
      </body>
    </html>
  );
}
